# Generated by Django 3.2 on 2023-10-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0002_alter_haircuts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haircuts',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Стрижка'),
        ),
    ]
