# Generated by Django 3.2 on 2023-10-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0004_auto_20231030_0036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotion',
            new_name='Promotions',
        ),
    ]
